### ISSUE TITLE
Ikasan shell to expose env configuration in non-interactive mode

### ISSUE THREAD

**Issue by davidhilton68** [ikasanEIP/ikasan#1198]
The ikasan shell currently allows the user to access the env in interactive mode as mentioned here - https://github.com/ikasanEIP/ikasan/tree/3.3.x/ikasaneip/ootb/module/scheduler-agent

What would be really handy is to get this in **non-interactive** mode

What would be even more useful is to support passing in a parameter e.g. env "h2.java.command" and getting back what that evaluates to.

**Use case**

- As a devops developer
- I would like to get access to the expanded version of env properties like h2.java.command
- So that I can include them in startup scripts like nssm

Part of  a typical nssm configuration script

nssm.exe set my-agent-h2  AppParameters "-server -Xms ..... h2.tools.server"
nssm.exe set my-agent  AppParameters "-server -Xms ..... command line paramsr"

**Comment by mitcje** [comment]
Created Ikasan-2221 in the atlassian Ikasan jira instance to track this
